### ISSUE TITLE
Package fails to build with stack and servant-0.5

### ISSUE THREAD

**Issue by qrilka** [imalsogreg/servant-reflex#15]
Using stack (see `stack.yaml` in my branch https://github.com/qrilka/servant-reflex/tree/stack-test)  I get the following compilation errors:
```
    /home/qrilka/ws/h/servant-reflex/src/Servant/Common/BaseUrl.hs:83:43:
        Ambiguous occurrence ‘apDyn’
        It could refer to either ‘Servant.Common.BaseUrl.apDyn’,
                                 defined at src/Servant/Common/BaseUrl.hs:86:1
                              or ‘Reflex.Dom.apDyn’,
                                 imported from ‘Reflex.Dom’ at src/Servant/Common/BaseUrl.hs:22:1-27
                                 (and originally defined in ‘Reflex.Dynamic’)
    
    /home/qrilka/ws/h/servant-reflex/src/Servant/Common/BaseUrl.hs:83:61:
        Ambiguous occurrence ‘apDyn’
        It could refer to either ‘Servant.Common.BaseUrl.apDyn’,
                                 defined at src/Servant/Common/BaseUrl.hs:86:1
                              or ‘Reflex.Dom.apDyn’,
                                 imported from ‘Reflex.Dom’ at src/Servant/Common/BaseUrl.hs:22:1-27
                                 (and originally defined in ‘Reflex.Dynamic’)
    
    /home/qrilka/ws/h/servant-reflex/src/Servant/Common/BaseUrl.hs:83:74:
        Ambiguous occurrence ‘apDyn’
        It could refer to either ‘Servant.Common.BaseUrl.apDyn’,
                                 defined at src/Servant/Common/BaseUrl.hs:86:1
                              or ‘Reflex.Dom.apDyn’,
                                 imported from ‘Reflex.Dom’ at src/Servant/Common/BaseUrl.hs:22:1-27
                                 (and originally defined in ‘Reflex.Dynamic’)
```

**Comment by imalsogreg** [comment]
Thank you for the report. I think you may be on a newer version of reflex-dom that exports its own `apDyn`. I've renamed the `apDyn` in `servant-reflex` to `myApDyn`. Would you please try pulling the latest change to `servant-reflex` and letting me know if the build works?

NB - when `servant-reflex` is released on Hackage I will pick dependency version bounds that prevent this kind of thing. Until then, sorry about the breakage :)

**Comment by qrilka** [comment]
thanks @imalsogreg - compiled perfectly
